// This transform config was generated by Snaplet.
// Snaplet found fields that may contain personally identifiable information (PII)
// and used that to populate this file.
import type { Transform } from './structure';
export const config: Transform = () => ({
  $options: {
    mode: 'unsafe',
  },
});
