-- NODES
create table
  public.nodes (
    id bigint generated by default as identity primary key,
    type text not null,
    title text not null,
    description text,
    coordinates numeric [2] not null,
    created_at timestamp
    with
      time zone default now() not null
  );


comment on table public.nodes is 'Map nodes.';


-- Secure the tables
alter table
  public.nodes enable row level security;


create policy "Enable delete for authorized users" on public.nodes as permissive for delete to public using (authorize('nodes.delete', auth.uid()));


create policy "Enable insert for authenticated users only" on public.nodes as permissive for insert to authenticated
with
  check (true);


create policy "Enable read access for all users" on public.nodes as permissive for
select
  to public using (true);


create policy "Enable update for authorized users" on public.nodes as permissive for
update
  to public using (authorize('nodes.edit', auth.uid()));


-- ASSIGN PERMISSIONS
insert into
  public.role_permissions (role, permission)
values
  ('admin', 'nodes.delete'),
  ('admin', 'nodes.edit'),
  ('moderator', 'nodes.delete'),
  ('moderator', 'nodes.edit');